name: Build, Push and Deploy to EKS

on:
  push:
    branches:
      - main
      - features/devops

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    name: Build, Push and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push microservices to ECR
      env:
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        services=("envios" "inventario" "pedidos" "usuario")
        for service in "${services[@]}"; do
          echo "Building smartlogix-$service..."
          docker build -t $ECR_REPOSITORY/smartlogix-$service:$IMAGE_TAG ./Backend
          docker push $ECR_REPOSITORY/smartlogix-$service:$IMAGE_TAG
          echo "✓ smartlogix-$service pushed successfully"
        done

    - name: Update Kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER }} --region ${{ env.AWS_REGION }}

    - name: Deploy to EKS
      env:
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        sed -i "s|\${IMAGE_TAG}|$IMAGE_TAG|g" k8s/backend.yml
        sed -i "s|ECR_REGISTRY|$ECR_REPOSITORY|g" k8s/backend.yml
        kubectl apply -f k8s/backend.yml
        echo "✓ Deployment completed"
